"""Add achievement_records table

Revision ID: ce5235a5470f
Revises: 05d9cda0c958
Create Date: 2026-01-26 15:22:50.748002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5235a5470f'
down_revision: Union[str, Sequence[str], None] = '05d9cda0c958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status_achieved', sa.Boolean(), nullable=False),
    sa.Column('status_score', sa.Float(), nullable=False),
    sa.Column('status_reason', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('evidence_metadata', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_records_milestone_id'), 'achievement_records', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_achievement_records_user_id'), 'achievement_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_achievement_records_user_id'), table_name='achievement_records')
    op.drop_index(op.f('ix_achievement_records_milestone_id'), table_name='achievement_records')
    op.drop_table('achievement_records')
    # ### end Alembic commands ###
